[package]
name = "bindgen-integration"
description = "A package to test various bindgen features"
version = "0.1.0"

build = "build.rs"
publish = false

authors.workspace = true
edition.workspace = true

[build-dependencies]
bindgen = { path = "../bindgen", features = ["experimental"] }
cc = "1.0"

[features]
static = ["bindgen/static"]
runtime = ["bindgen/runtime"]

testing_only_extra_assertions = ["bindgen/testing_only_extra_assertions"]
testing_only_libclang_9 = ["bindgen/testing_only_libclang_9"]
testing_only_libclang_5 = ["bindgen/testing_only_libclang_5"]
