[package]
name = "bindgen-cli"

rust-version = "1.64.0"

authors.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "bindgen"
path = "main.rs"

[dependencies]
bindgen = { path = "../bindgen", version = "=0.64.0", features = ["cli", "experimental"] }
shlex = "1"
clap = { version = "4", features = ["derive"] }
env_logger = { version = "0.10.0", optional = true }
log = { version = "0.4", optional = true }

[features]
default = ["logging", "runtime", "which-rustfmt"]
logging = ["bindgen/logging", "env_logger", "log"]
static = ["bindgen/static"]
runtime = ["bindgen/runtime"]
# Dynamically discover a `rustfmt` binary using the `which` crate
which-rustfmt = ["bindgen/which-rustfmt"]
